// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ8f4ilHYqiugoyBtjCFYjVCs5hlS7Lws',
    appId: '1:402836562976:web:328e33b31742995a520845',
    messagingSenderId: '402836562976',
    projectId: 'farmerappdemo-5fda3',
    authDomain: 'farmerappdemo-5fda3.firebaseapp.com',
    storageBucket: 'farmerappdemo-5fda3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsgfORhjJC0uhAdIVK0z4z8iLSbaBtfT4',
    appId: '1:402836562976:android:49bcdb6dea6b86b4520845',
    messagingSenderId: '402836562976',
    projectId: 'farmerappdemo-5fda3',
    storageBucket: 'farmerappdemo-5fda3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB60OX4PN9Uo1q8Obw5qgM-YkINGbk-B5M',
    appId: '1:402836562976:ios:1686894d66152a89520845',
    messagingSenderId: '402836562976',
    projectId: 'farmerappdemo-5fda3',
    storageBucket: 'farmerappdemo-5fda3.appspot.com',
    iosClientId: '402836562976-sv3j61saetisnmmudqplppp1hd3omcuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmerappdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB60OX4PN9Uo1q8Obw5qgM-YkINGbk-B5M',
    appId: '1:402836562976:ios:1686894d66152a89520845',
    messagingSenderId: '402836562976',
    projectId: 'farmerappdemo-5fda3',
    storageBucket: 'farmerappdemo-5fda3.appspot.com',
    iosClientId: '402836562976-sv3j61saetisnmmudqplppp1hd3omcuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmerappdemo',
  );
}
